### ISSUE TITLE
Background gradient does not loop seamlessly

### ISSUE THREAD

**Issue by soni801** [LilleAndersen/LilleAndersen.github.io#2]
**Description**
The animated background gradient found on all your pages does not loop seamlessly but does however make a small jump when it loops. This does not look good and ruins the immersion

**To Reproduce**
1. Go to [your website](https://little.yessness.com/)
2. Wait for the background gradient to loop

**Expected behaviour**
The background loops seamlessly, not showing to the user that it loops.

**Device info**
 - OS: Microsoft Windows 10 Home 21H1 Version 2009 Build 19043.985
 - Browser: Microsoft Edge (Chromium)
 - Version: 91.0.864.37 (64-bit)

**Comment by LilleAndersen** [comment]
soni good at comment not
