### ISSUE TITLE
Preloader is selectable

### ISSUE THREAD

**Issue by soni801** [LilleAndersen/LilleAndersen.github.io#3]
**Description**
The preloader can be selected by the user. This also has the side effect of looking bad if the user clicks a link in the header too fast. [Screenshot](https://i.imgur.com/wku0xrj.png).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [your website](https://little.yessness.com/)
2. Try to select the preloader. This can be done by double-clicking or dragging over it like you would select any text.

**Expected behaviour**
The preloader is not user-selectable.

**Comment by LilleAndersen** [comment]
This is now fixed
