### ISSUE TITLE
Copyright notice has higher y-index than header

### ISSUE THREAD

**Issue by soni801** [LilleAndersen/LilleAndersen.github.io#4]
**Description**
The copyright notice has a higher y-index than the header. This causes it to overlay on top when scrolling.

**To Reproduce**
1. Go to [your website](https://little.yessness.com/)
2. Navigate to the `Skole` page
3. Scroll slowly

**Expected behavior**
The header is on top of the copyright notice.

**Screenshots**
![](https://i.imgur.com/wwjhlWj.png)
![](https://i.imgur.com/b51470F.png)

**Comment by LilleAndersen** [comment]
This is now fixed
